# Generated by Django 5.2.4 on 2025-07-24 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MorphometricMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='goat_images/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='goat_images/processed/')),
                ('hauteur_au_garrot', models.DecimalField(blank=True, decimal_places=2, help_text='Wither Height (WH) - cm', max_digits=6, null=True)),
                ('hauteur_au_dos', models.DecimalField(blank=True, decimal_places=2, help_text='Back Height (BH) - cm', max_digits=6, null=True)),
                ('hauteur_au_sternum', models.DecimalField(blank=True, decimal_places=2, help_text='Sternum Height (SH) - cm', max_digits=6, null=True)),
                ('hauteur_au_sacrum', models.DecimalField(blank=True, decimal_places=2, help_text='Rump Height (RH) - cm', max_digits=6, null=True)),
                ('tour_de_poitrine', models.DecimalField(blank=True, decimal_places=2, help_text='Heart Girth (HG) - cm', max_digits=6, null=True)),
                ('perimetre_thoracique', models.DecimalField(blank=True, decimal_places=2, help_text='Chest Circumference (CC) - cm', max_digits=6, null=True)),
                ('tour_abdominal', models.DecimalField(blank=True, decimal_places=2, help_text='Abdominal Girth (AG) - cm', max_digits=6, null=True)),
                ('tour_du_cou', models.DecimalField(blank=True, decimal_places=2, help_text='Neck Girth (NG) - cm', max_digits=6, null=True)),
                ('diametre_biscotal', models.DecimalField(blank=True, decimal_places=2, help_text='Bi-costal Diameter (BD) - cm', max_digits=6, null=True)),
                ('largeur_poitrine', models.DecimalField(blank=True, decimal_places=2, help_text='Chest Width (CW) - cm', max_digits=6, null=True)),
                ('largeur_hanche', models.DecimalField(blank=True, decimal_places=2, help_text='Rump Width (RW) - cm', max_digits=6, null=True)),
                ('largeur_tete', models.DecimalField(blank=True, decimal_places=2, help_text='Head Width (HW) - cm', max_digits=6, null=True)),
                ('body_length', models.DecimalField(blank=True, decimal_places=2, help_text='Body Length (BL) - cm', max_digits=6, null=True)),
                ('longueur_oreille', models.DecimalField(blank=True, decimal_places=2, help_text='Ear Length (EL) - cm', max_digits=6, null=True)),
                ('longueur_tete', models.DecimalField(blank=True, decimal_places=2, help_text='Head Length (HL) - cm', max_digits=6, null=True)),
                ('longueur_cou', models.DecimalField(blank=True, decimal_places=2, help_text='Neck Length (NL) - cm', max_digits=6, null=True)),
                ('longueur_queue', models.DecimalField(blank=True, decimal_places=2, help_text='Tail Length (TL) - cm', max_digits=6, null=True)),
                ('measurement_method', models.CharField(choices=[('AUTO', 'Automatic AI Detection'), ('MANUAL', 'Manual Input'), ('HYBRID', 'AI-Assisted with Manual Correction')], default='AUTO', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, help_text='AI confidence score (0-1)', max_digits=4, null=True)),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('reference_object_length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Known length of reference object in image', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.goat')),
                ('measured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the keypoint (e.g., 'wither', 'sternum', etc.)", max_length=50)),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('manually_adjusted', models.BooleanField(default=False)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='measurements.morphometricmeasurement')),
            ],
        ),
    ]
