# Generated by Django 5.0.7 on 2025-08-02 21:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='measurementsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='goat',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AlterField(
            model_name='morphometricmeasurement',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='AI confidence score (0-1)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='morphometricmeasurement',
            name='reference_object_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Known length of reference object in image', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddIndex(
            model_name='goat',
            index=models.Index(fields=['owner', '-created_at'], name='measurement_owner_i_41ec2a_idx'),
        ),
        migrations.AddIndex(
            model_name='goat',
            index=models.Index(fields=['breed'], name='measurement_breed_bb50fb_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementsession',
            index=models.Index(fields=['user', '-created_at'], name='measurement_user_id_8cc6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='morphometricmeasurement',
            index=models.Index(fields=['measurement_date'], name='measurement_measure_be14f6_idx'),
        ),
        migrations.AddIndex(
            model_name='morphometricmeasurement',
            index=models.Index(fields=['goat', 'measurement_date'], name='measurement_goat_id_560ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='morphometricmeasurement',
            index=models.Index(fields=['measured_by'], name='measurement_measure_b05d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='morphometricmeasurement',
            index=models.Index(fields=['measurement_method'], name='measurement_measure_1be06d_idx'),
        ),
    ]
