# Generated by Django 5.2.4 on 2025-08-03 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_goat_options_alter_measurementsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='goat_images/batch/')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order in which image was uploaded')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['session', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='failed_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='goat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurements.goat'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='processed_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='total_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='measurementsession',
            index=models.Index(fields=['status'], name='measurement_status_53730b_idx'),
        ),
        migrations.AddField(
            model_name='batchimageupload',
            name='measurement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_upload', to='measurements.morphometricmeasurement'),
        ),
        migrations.AddField(
            model_name='batchimageupload',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_images', to='measurements.measurementsession'),
        ),
        migrations.AddIndex(
            model_name='batchimageupload',
            index=models.Index(fields=['session', 'status'], name='measurement_session_da155e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchimageupload',
            index=models.Index(fields=['status'], name='measurement_status_5224c0_idx'),
        ),
    ]
